### PR TITLE
composer.json 'scripts' entries can be strings

### LINKED ISSUE #90: Composer.json scripts do not support strings
After moving from `heroku/buildpacks:20` to `heroku/builder:22`, composer.json parsing fails when using strings in scripts. 
This is noted as valid syntax from Composer: https://getcomposer.org/doc/articles/scripts.md#defining-scripts 

> An event's scripts can be defined as either a string (only for a single script) or an array (for single or multiple scripts.)

```===> BUILDING
[builder] 
[builder] [Error: Failed to parse 'composer.json']
[builder] The parsed contents were invalid.
[builder] 
[builder] Details: invalid type: string "phpcbf", expected a sequence at line 100 column 1
[builder] 
[builder] Please run 'composer validate' on your local computer for verification.
[builder] 
[builder] If you believe this message to be in error, please report it.
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
```

Example composer.json:

```"scripts": {
        "compile": [
            "bin/doctrine orm:generate-proxies"
        ],
        "cs": [
            "phpcs"
        ],
        "cs:fix": "phpcbf",
        "test": "phpunit",
        "test:ordered": [
            "phpunit --testsuite unit",
            "phpunit --testsuite functional"
        ],
        "serve": "php -S 0.0.0.0:8080 -t public/"
    }
```

This is resolved when moving the strings into arrays:

```
"cs:fix": [
    "phpcbf"
 ],
```

### PR DESCRIPTION
**Pull request by dzuelke**
Each value in the object can be a string for a single command, or list of commands:

```json
{
  "scripts": {
    "foo": [
      "first-command",
      "second-command"
    ],
    "bar": "another-command"
  }
}
```

Fixes #90

### CODE REVIEW

File: composer/src/lib.rs [hunk 1]
```diff
@@ -118,6 +118,7 @@ pub struct ComposerBasePackage {
     pub repositories: Option<Vec<ComposerRepository>>,
     pub require: Option<HashMap<String, String>>,
     pub require_dev: Option<HashMap<String, String>>,
+    #[serde_as(as = "Option<HashMap<_, OneOrMany<_, PreferOne>>>")]
```
Comment (colincasey) [inline composer/src/lib.rs:121]: Had to go searching for [the docs](https://docs.rs/serde_with/3.7.0/serde_with/struct.OneOrMany.html) to understand this annotation. It seems like this would cover your requirement. Is there an existing test that verifies this or do you plan on adding one @dzuelke?

Comment (dzuelke) [reply composer/src/lib.rs:121]: I added a little something, @colincasey, but the `composer` sub-crate will eventually get a whole battery of tests (gotta generate all the fixtures first, it's... a lot!)

**Review by edmorley — APPROVED** [review]
