### PR TITLE
Handle "non-URL" URLs in packages and repositories consistently

### LINKED ISSUE #187: Cannot parse git@ urls error: relative URL without a base
This comment on https://github.com/heroku/buildpacks-php/issues/105#issuecomment-2819347153 is a related but different issue than the one I fixed. I'm opening a new issue for it. Comment:

-----
```
"repositories":  [ 
  { "type": "composer", "url": "https://my.yoast.com/packages/" }, 
  { "type": "composer", "url": "https://wpackagist.org" } 
]

```
It reports the following error:

```
[Error: Failed to parse 'composer.lock']
There was an error parsing the lock file; it must be a valid
file generated by Composer and be in an up-to-date state.
Check below for any parse errors and address them if necessary.
The parsed contents were invalid.
Details: relative URL without a base: "git@github.com:Yoast-dist/wordpress-seo-premium.git" at line 7137 column 9
```
-----

@ngatti-tmm Can you please share your `composer.json` and `composer.lock` in this issue? You can remove anything that's not needed to reproduce the problem if you don't want to share everything https://www.codetriage.com/reproduction. If you're unable to share in public, and have a heroku account, you open a support ticket and reference this issue to share those files privately. 

[W-18352395](https://gus.lightning.force.com/a07EE00002DMOw7YAH)

### PR DESCRIPTION
**Pull request by dzuelke**
Both `ComposerPackageSource` and `ComposerPackageDist` may contain "non-URL" URLs such as paths (see #105) or SSH style `git@github.com:foo/bar.git` URLs.

The same is true for many ComposerRepository variants, where a 'composer' type repository may use a relative path, or a 'vcs'/'git' type repository may use an SSH style Git URL.

Refs #105 (which #176 partially fixed, but by simply removing the field).

Closes #187

Supersedes #194

GUS-W-18768244

### CODE REVIEW

File: composer/src/lib.rs [hunk 1]
```diff
@@ -455,13 +543,13 @@ mod tests {
...
         let composer_json = fs::read(&path).unwrap();
-        serde_json::from_slice::<ComposerRootPackage>(&composer_json).unwrap();
+        dbg!(serde_json::from_slice::<ComposerRootPackage>(&composer_json).unwrap());
     }
 
     #[rstest]
     fn test_composer_lock(#[files("tests/fixtures/*.lock")] path: PathBuf) {
         let composer_lock = fs::read(&path).unwrap();
-        serde_json::from_slice::<ComposerLock>(&composer_lock).unwrap();
+        dbg!(serde_json::from_slice::<ComposerLock>(&composer_lock).unwrap());
```
Comment (schneems) [inline composer/src/lib.rs:552]: I'm not sure the purpose of these print statements. Can we remove them or annotate why they're here?

```suggestion
        serde_json::from_slice::<ComposerLock>(&composer_lock).unwrap();
```

**Review by schneems — DISMISSED** [review]
I'm able to delete a lot of the code you added and tests still pass. It appears either they're not used, or they're used but not exercised under test in a way that a real world deploy would use them. 

If these fields are needed, it's unclear why. Please add tests that would fail in the same way a real world app would fail if this code did not exist. 

i.e. I'm assuming you'll add some validation or presence check to the composer.lock. With that, let's also validate that those assertions represent observable behavior changes and document that in code. Ideally, the failure message should be clear to the developer, so that if my change that you reverted was problematic for some reason, that tests would both catch the problem and enumerate the reason why it's a problem.

```diff
$ git diff
diff --git a/composer/src/lib.rs b/composer/src/lib.rs
index b296cd6..38e497a 100644
--- a/composer/src/lib.rs
+++ b/composer/src/lib.rs
@@ -264,42 +264,15 @@ pub struct ComposerPackageArchive {
 #[serde(untagged)]
 pub enum ComposerPackageDist {
     #[serde(rename_all = "kebab-case")]
-    Path {
-        #[serde(rename = "type")]
-        kind: MustBe!("path"),
-        url: PathBuf,
-        reference: Option<String>,
-        shasum: Option<String>,
-    },
+    Path {},
     #[serde(rename_all = "kebab-case")]
-    Url {
-        #[serde(rename = "type")]
-        kind: String,
-        url: Url,
-        reference: Option<String>,
-        shasum: Option<String>,
-        mirrors: Option<Vec<ComposerMirror<Url>>>,
-    },
-}
-
-#[serde_as]
-#[skip_serializing_none]
-#[derive(Clone, Debug, Deserialize, Serialize)]
-pub struct ComposerPackageSource {
-    #[serde(rename = "type")]
-    pub kind: String,
-    pub url: ComposerUrlOrSshOrPathUrl,
-    pub reference: Option<String>,
-    pub mirrors: Option<Vec<ComposerMirror<ComposerUrlOrSshOrPathUrl>>>,
+    Url {},
 }

 #[serde_as]
 #[skip_serializing_none]
 #[derive(Clone, Debug, Deserialize, Serialize)]
-pub struct ComposerMirror<T> {
-    pub url: T,
-    pub preferred: bool,
-}
+pub struct ComposerPackageSource {}
```

**Comment by dzuelke** [comment]
> I'm able to delete a lot of the code you added and tests still pass. It appears either they're not used, or they're used but not exercised under test in a way that a real world deploy would use them.

That's how serde works for self-describing formats like JSON - unknown fields are ignored by default. So when you delete that code, during parsing, it doesn't have any suitable mapping, and discards the info.

> If these fields are needed, it's unclear why. Please add tests that would fail in the same way a real world app would fail if this code did not exist.
> 
> i.e. I'm assuming you'll add some validation or presence check to the composer.lock. With that, let's also validate that those assertions represent observable behavior changes and document that in code. Ideally, the failure message should be clear to the developer, so that if my change that you reverted was problematic for some reason, that tests would both catch the problem and enumerate the reason why it's a problem.

The reason why these are implemented is because we write out, in our "platform" `composer.json`, some of the `ComposerRepository` variants, which can have the same general URL issues (a relative path for a `composer` repo `url`, say).

The resulting `composer.lock` that Composer produces for our `composer.json` should then be readable by us (without data getting dropped during deserialization).

And having the `url` working for some `ComposerRepository` variants but not even present for others seems quite inconsistent, even if our logic doesn't write, say, a `vcs` repo with an SSH style URL, or an inline `package` with a relative path `url` in `source`.

**Comment by schneems** [comment]
Checking in. What are next steps?

**Comment by schneems** [comment]
Following up here: My main concern with this approach to fixing the issue is that it must be coupled with a fast-follow for any fixes if there are breakages due to our json parsing being overly strict (in fields we do not use). While I previously suggested that using a `String` is a middle -of-the-road solution. I'm now leaning back to deleting the fields altogether, given the pace of changes we're able to deliver.

**Comment by dzuelke** [comment]
Thought about this some more:

> Pivoting a bit: If you want to move forwards without introducing a test that exercises the URL fields you've re-added here, then I suggest a different approach to use a String instead. The composer spec is not strong enough for us to make any assumptions about the format inside of the String.
>
> I also suggest we re-prioritize otel/metrics to log and quantify json parsing failures. The strict parsing of the composer.json seems to be the largest cause of bugs on this buildpack and would seem to confirm my worry.

We now parse URLs into `PathBuf` as the "last resort" step for anything that appears malformed, which is infallible. We haven't received any other reports of issues around URLs in `composer.json` or `composer.lock`, so IMO this is sufficient for now.

File: buildpacks/php/CHANGELOG.md [hunk 2]
```diff
@@ -44,6 +44,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - ext-grpc/1.73.0
 - librdkafka/2.10.1
 
+### Changed
+
+- Consistent handling of "non-URL" URLs (SSH-style or path) in `composer.json`/`composer.lock` repositories and package `source`s/`dist`s ([#105](https://github.com/heroku/buildpacks-php/issue/105), [#187](https://github.com/heroku/buildpacks-php/issue/187), [#208](https://github.com/heroku/buildpacks-php/pull/208))
```
Comment (edmorley) [inline buildpacks/php/CHANGELOG.md:49]: This changelog entry needs moving under `[unreleased]`
